services:
  - type: web
    name: numerologi-tiktok-listener
    runtime: node
    plan: free
    rootDir: listener
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: TIKTOK_USERNAME
        sync: false
      - key: ADMIN_TOKEN
        sync: false
